# In this notebook, we are going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically we're going to cover :


> Indented block
* Introduction to tensors
* Getting informations from tensors
* Manipulating tensors
* Tensors and NumPy
*Using @tf.function(a way to speed up your regular Python functons)
*Using GPUs with TensorFlow(or TPUs)
*Exercises to your self!








## Introduction to Tensors

In [3]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [6]:
#Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
#Check the number of dimensions of a tensor(ndim stands for number of dimensions)
scalar.ndim

0

In [8]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [9]:
vector.ndim

1

In [10]:
# Create a matrix (has more than 1 dimensions)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [11]:
# Check dimensions of a matrix
matrix.ndim

2

In [12]:
#Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype = tf.float16) # specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [13]:
#Check dimensions of another matrix
another_matrix.ndim

2